Repository MyPet-Sparta5/Mypet, pull requests merged in 2024-07, with the labels that each got.

#2 [2024/07/19]feat/#1 project settings
  .gitignore
  docker-compose.yml
  src/main/java/com/sparta/mypet/MypetApplication.java
  src/main/java/com/sparta/mypet/common/Timestamped.java
  src/main/java/com/sparta/mypet/domain/auth/UserRepository.java
  src/main/java/com/sparta/mypet/domain/auth/entity/User.java
  src/main/java/com/sparta/mypet/domain/auth/entity/UserRoleEnum.java
  src/main/java/com/sparta/mypet/domain/auth/entity/UserStatusEnum.java
  src/main/java/com/sparta/mypet/domain/comment/CommentRepository.java
  src/main/java/com/sparta/mypet/domain/comment/entity/Comment.java
  src/main/java/com/sparta/mypet/domain/like/LikeRepository.java
  src/main/java/com/sparta/mypet/domain/like/entity/Like.java
  src/main/java/com/sparta/mypet/domain/post/PostRepository.java
  src/main/java/com/sparta/mypet/domain/post/entity/File.java
  src/main/java/com/sparta/mypet/domain/post/entity/Post.java
  src/main/java/com/sparta/mypet/domain/report/ReportRepository.java
  src/main/java/com/sparta/mypet/domain/report/entity/Report.java
  src/main/java/com/sparta/mypet/domain/report/entity/ReportStatus.java
  src/main/resources/application.properties
Labels: feat

#10 [2024/07/20] feat/#9 common response
  src/main/java/com/sparta/mypet/common/dto/DataResponseDto.java
  src/main/java/com/sparta/mypet/common/dto/MessageResponseDto.java
  src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
  src/main/java/com/sparta/mypet/common/entity/Timestamped.java
  src/main/java/com/sparta/mypet/common/util/ResponseFactory.java
  src/main/java/com/sparta/mypet/domain/auth/entity/User.java
  src/main/java/com/sparta/mypet/domain/comment/entity/Comment.java
  src/main/java/com/sparta/mypet/domain/post/entity/Post.java
  src/main/java/com/sparta/mypet/domain/report/entity/Report.java
Labels: feat

#12 [2024/07/21] feat/#11 exception handler
  src/main/java/com/sparta/mypet/common/exception/GlobalExceptionHandler.java
Labels: feat

#14 [2024/07/21]feat/#13 signup
  src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
  src/main/java/com/sparta/mypet/common/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/mypet/common/exception/auth/PasswordInvalidException.java
  src/main/java/com/sparta/mypet/common/exception/auth/UserEmailDuplicateException.java
  src/main/java/com/sparta/mypet/common/initialization/DataInitialization.java
  src/main/java/com/sparta/mypet/domain/auth/UserController.java
  src/main/java/com/sparta/mypet/domain/auth/UserRepository.java
  src/main/java/com/sparta/mypet/domain/auth/UserService.java
  src/main/java/com/sparta/mypet/domain/auth/config/PasswordConfig.java
  src/main/java/com/sparta/mypet/domain/auth/dto/SignupRequestDto.java
  src/main/java/com/sparta/mypet/domain/auth/dto/SignupResponseDto.java
  src/main/java/com/sparta/mypet/domain/auth/entity/User.java
  src/main/java/com/sparta/mypet/domain/auth/entity/UserRole.java
  src/main/java/com/sparta/mypet/domain/auth/entity/UserStatus.java
  src/main/resources/application.properties
Labels: feat, refactor

#15 [2024/07/21]feat/#3 get comments
  src/main/java/com/sparta/mypet/domain/comment/CommentController.java
  src/main/java/com/sparta/mypet/domain/comment/CommentRepository.java
  src/main/java/com/sparta/mypet/domain/comment/CommentService.java
  src/main/java/com/sparta/mypet/domain/comment/dto/CommentResponseDto.java
Labels: feat

#16 [2024/07/21]feat/#4 create comment
  src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
  src/main/java/com/sparta/mypet/common/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/mypet/common/exception/PostNotFoundException.java
  src/main/java/com/sparta/mypet/domain/comment/CommentController.java
  src/main/java/com/sparta/mypet/domain/comment/CommentService.java
  src/main/java/com/sparta/mypet/domain/comment/dto/CommentRequestDto.java
  src/main/java/com/sparta/mypet/domain/comment/dto/CommentResponseDto.java
Labels: feat

#17 [2024/07/22]feat/#5 delete comment
  src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
  src/main/java/com/sparta/mypet/common/exception/CommentNotFoundException.java
  src/main/java/com/sparta/mypet/common/util/ResponseFactory.java
  src/main/java/com/sparta/mypet/domain/comment/CommentController.java
  src/main/java/com/sparta/mypet/domain/comment/CommentService.java
Labels: feat

#26 [2024/07/22]feat/#8 post create
  build.gradle
  src/main/java/com/sparta/mypet/common/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/mypet/domain/post/PostController.java
  src/main/java/com/sparta/mypet/domain/post/PostService.java
  src/main/java/com/sparta/mypet/domain/post/dto/PostRequestDto.java
  src/main/java/com/sparta/mypet/domain/post/dto/PostResponseDto.java
  src/main/java/com/sparta/mypet/domain/post/entity/Category.java
  src/main/java/com/sparta/mypet/domain/post/entity/Post.java
Labels: feat

#33 [2024/07/22]feat/#20 update post
  src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
  src/main/java/com/sparta/mypet/common/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/mypet/common/exception/UserMisMatchException.java
  src/main/java/com/sparta/mypet/domain/post/PostController.java
  src/main/java/com/sparta/mypet/domain/post/PostRepository.java
  src/main/java/com/sparta/mypet/domain/post/PostService.java
  src/main/java/com/sparta/mypet/domain/post/dto/PostRequestDto.java
  src/main/java/com/sparta/mypet/domain/post/dto/PostResponseDto.java
  src/main/java/com/sparta/mypet/domain/post/entity/Post.java
Labels: feat

#34 [2024/07/22]feat/#6 create like
  src/main/java/com/sparta/mypet/domain/comment/dto/CommentRequestDto.java
  src/main/java/com/sparta/mypet/domain/like/LikeController.java
  src/main/java/com/sparta/mypet/domain/like/LikeService.java
Labels: feat

#36 [2024/07/22] feat/#21 post delete
  src/main/java/com/sparta/mypet/domain/post/PostController.java
  src/main/java/com/sparta/mypet/domain/post/PostService.java
  src/main/java/com/sparta/mypet/domain/post/dto/PostResponseDto.java
Labels: feat

#37 [2024/07/22] feat/#22 get posts
  src/main/java/com/sparta/mypet/domain/post/PostController.java
  src/main/java/com/sparta/mypet/domain/post/PostService.java
  src/main/java/com/sparta/mypet/domain/post/dto/PostResponseDto.java
Labels: feat

#38 [2024/07/22] feat/#35 comment page
  src/main/java/com/sparta/mypet/common/util/PaginationUtil.java
  src/main/java/com/sparta/mypet/domain/comment/CommentController.java
  src/main/java/com/sparta/mypet/domain/comment/CommentRepository.java
  src/main/java/com/sparta/mypet/domain/comment/CommentService.java
  src/main/java/com/sparta/mypet/domain/comment/dto/CommentPageResponse.java
Labels: feat

#40 [2024/07/22] feat/#23 get post
  src/main/java/com/sparta/mypet/domain/post/PostController.java
  src/main/java/com/sparta/mypet/domain/post/PostService.java
  src/main/java/com/sparta/mypet/domain/post/dto/PostResponseDto.java
Labels: feat

#41 [2024/07/22] feat/#7 delete like
  src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
  src/main/java/com/sparta/mypet/common/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/mypet/common/exception/custom/LikeNotFoundException.java
  src/main/java/com/sparta/mypet/domain/like/LikeController.java
  src/main/java/com/sparta/mypet/domain/like/LikeRepository.java
  src/main/java/com/sparta/mypet/domain/like/LikeService.java
Labels: feat

#42 [2024/07/22] refactor/#39 refactor post
  src/main/java/com/sparta/mypet/domain/post/PostController.java
  src/main/java/com/sparta/mypet/domain/post/PostService.java
Labels: refactor

#43 [2024/07/23]feat/#25 security login
  build.gradle
  src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
  src/main/java/com/sparta/mypet/common/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/mypet/common/exception/custom/CommentNotFoundException.java
  src/main/java/com/sparta/mypet/common/exception/custom/PasswordInvalidException.java
  src/main/java/com/sparta/mypet/common/exception/custom/PostNotFoundException.java
  src/main/java/com/sparta/mypet/common/exception/custom/UserEmailDuplicateException.java
  src/main/java/com/sparta/mypet/common/exception/custom/UserMisMatchException.java
  src/main/java/com/sparta/mypet/common/initialization/DataInitialization.java
  src/main/java/com/sparta/mypet/domain/auth/AuthController.java
  src/main/java/com/sparta/mypet/domain/auth/AuthService.java
  src/main/java/com/sparta/mypet/domain/auth/UserService.java
  src/main/java/com/sparta/mypet/domain/auth/dto/LoginRequestDto.java
  src/main/java/com/sparta/mypet/domain/auth/entity/User.java
  src/main/java/com/sparta/mypet/domain/comment/CommentService.java
  src/main/java/com/sparta/mypet/domain/like/LikeService.java
  src/main/java/com/sparta/mypet/domain/post/PostService.java
  src/main/java/com/sparta/mypet/security/JwtService.java
  src/main/java/com/sparta/mypet/security/UserDetailsImpl.java
  src/main/java/com/sparta/mypet/security/UserDetailsServiceImpl.java
  src/main/java/com/sparta/mypet/security/config/JwtConfig.java
  src/main/java/com/sparta/mypet/security/config/WebSecurityConfig.java
  src/main/java/com/sparta/mypet/security/filter/JwtAuthorizationFilter.java
  src/main/java/com/sparta/mypet/security/util/JwtProvider.java
  src/main/resources/application.properties
Labels: feat

#46 [2024/07/23]fix/#45 like bugfix
  http-client.env.json
  src/main/java/com/sparta/mypet/domain/comment/CommentController.java
  src/main/java/com/sparta/mypet/domain/like/LikeController.java
  src/main/java/com/sparta/mypet/domain/like/entity/Like.java
  src/main/java/com/sparta/mypet/security/config/WebSecurityConfig.java
  test.http
Labels: fix

#47 [2024/07/23] fix : Post UserDetails -> UserDetailsImpl 변경
  http/comment.http
  http/http-client.env.json
  http/like.http
  http/post.http
  http/user.http
  src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
  src/main/java/com/sparta/mypet/common/exception/custom/UserNotFoundException.java
  src/main/java/com/sparta/mypet/domain/auth/UserService.java
  src/main/java/com/sparta/mypet/domain/post/PostController.java
  src/main/java/com/sparta/mypet/domain/post/PostService.java
  test.http
Labels: refactor

#48 [2024/07/23]feat/#28 logout
  http/user.http
  src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
  src/main/java/com/sparta/mypet/domain/auth/AuthController.java
  src/main/java/com/sparta/mypet/domain/auth/AuthService.java
  src/main/java/com/sparta/mypet/domain/auth/UserService.java
  src/main/java/com/sparta/mypet/security/JwtService.java
Labels: feat

#50 [2024/07/23] fix/#49 postResponseDto isLike
  http/post.http
  http/user.http
  src/main/java/com/sparta/mypet/domain/post/PostController.java
  src/main/java/com/sparta/mypet/domain/post/PostService.java
  src/main/java/com/sparta/mypet/domain/post/dto/PostResponseDto.java
Labels: fix

#51 [2024/07/23]feat/#31 refresh access token
  http/user.http
  src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
  src/main/java/com/sparta/mypet/common/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/mypet/common/exception/custom/RefreshTokenInvalidException.java
  src/main/java/com/sparta/mypet/domain/auth/AuthController.java
  src/main/java/com/sparta/mypet/domain/auth/AuthService.java
  src/main/java/com/sparta/mypet/security/JwtService.java
  src/main/java/com/sparta/mypet/security/TokenType.java
  src/main/java/com/sparta/mypet/security/config/WebSecurityConfig.java
  src/main/java/com/sparta/mypet/security/filter/JwtAuthorizationFilter.java
  src/main/java/com/sparta/mypet/security/util/JwtProvider.java
Labels: feat

#52 [2024/07/24]feat/#30 get user
  http/user.http
  src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
  src/main/java/com/sparta/mypet/domain/auth/UserController.java
  src/main/java/com/sparta/mypet/domain/auth/UserService.java
  src/main/java/com/sparta/mypet/domain/auth/dto/UserWithPostListResponseDto.java
  src/main/java/com/sparta/mypet/domain/auth/entity/User.java
  src/main/java/com/sparta/mypet/domain/post/dto/PostMappedUserResponseDto.java
Labels: feat

#58 [2024/07/24] feat/#27 aws s3
  build.gradle
  http/post.http
  src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
  src/main/java/com/sparta/mypet/common/exception/custom/InvalidFileException.java
  src/main/java/com/sparta/mypet/domain/post/PostController.java
  src/main/java/com/sparta/mypet/domain/post/PostRepository.java
  src/main/java/com/sparta/mypet/domain/post/PostService.java
  src/main/java/com/sparta/mypet/domain/post/dto/PostResponseDto.java
  src/main/java/com/sparta/mypet/domain/post/entity/File.java
  src/main/java/com/sparta/mypet/domain/post/entity/Post.java
  src/main/java/com/sparta/mypet/domain/s3/FileRepository.java
  src/main/java/com/sparta/mypet/domain/s3/FileResponseDto.java
  src/main/java/com/sparta/mypet/domain/s3/FileService.java
  src/main/java/com/sparta/mypet/domain/s3/S3Config.java
  src/main/java/com/sparta/mypet/domain/s3/entity/File.java
  src/main/java/com/sparta/mypet/domain/s3/entity/FileContentType.java
  src/main/resources/application.properties
Labels: feat

#59 [2024/07/24]feat/#29 withdraw user
  http/post.http
  http/user.http
  src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
  src/main/java/com/sparta/mypet/common/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/mypet/common/exception/custom/UserStatusNotActiveException.java
  src/main/java/com/sparta/mypet/domain/auth/AuthController.java
  src/main/java/com/sparta/mypet/domain/auth/AuthService.java
  src/main/java/com/sparta/mypet/domain/auth/UserController.java
  src/main/java/com/sparta/mypet/domain/auth/UserService.java
  src/main/java/com/sparta/mypet/domain/auth/dto/UserWithdrawResponseDto.java
  src/main/java/com/sparta/mypet/domain/auth/entity/User.java
  src/main/java/com/sparta/mypet/domain/auth/entity/UserStatus.java
Labels: feat

#60 [2024/07/24]feat/#32 create report user
  http/report.http
  src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
  src/main/java/com/sparta/mypet/domain/auth/UserService.java
  src/main/java/com/sparta/mypet/domain/report/ReportController.java
  src/main/java/com/sparta/mypet/domain/report/ReportRepository.java
  src/main/java/com/sparta/mypet/domain/report/ReportService.java
  src/main/java/com/sparta/mypet/domain/report/dto/ReportRequestDto.java
  src/main/java/com/sparta/mypet/domain/report/dto/ReportResponseDto.java
  src/main/java/com/sparta/mypet/domain/report/entity/Report.java
Labels: feat

#63 [2024/07/25]fix/#62 Dto 오류 수정
  src/main/java/com/sparta/mypet/domain/petcare/dto/PetFacilityDto.java
Labels: bug, fix

#64 [2024/07/25]feat/#53 backoffice userList
  http/backoffice.http
  src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeController.java
  src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeService.java
  src/main/java/com/sparta/mypet/domain/backoffice/dto/UserListResponseDto.java
  src/main/java/com/sparta/mypet/security/config/WebSecurityConfig.java
Labels: feat

#65 [2024/07/25]feat/#54 user status edit
  http/backoffice.http
  http/http-client.env.json
  src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeController.java
  src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeService.java
  src/main/java/com/sparta/mypet/domain/backoffice/dto/UserStatusRequestDto.java
  src/main/java/com/sparta/mypet/domain/backoffice/dto/UserStatusResponseDto.java
Labels: feat

#67 [2024/07/25]feat/#55 user role edit
  http/backoffice.http
  src/main/java/com/sparta/mypet/domain/auth/entity/User.java
  src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeController.java
  src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeService.java
  src/main/java/com/sparta/mypet/domain/backoffice/dto/UserRoleRequestDto.java
  src/main/java/com/sparta/mypet/domain/backoffice/dto/UserRoleResponseDto.java
  src/main/java/com/sparta/mypet/security/config/WebSecurityConfig.java
Labels: feat

#68 [2024/07/25]refactor/#66 post file refactor
  src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
  src/main/java/com/sparta/mypet/common/exception/custom/InvalidCategoryException.java
  src/main/java/com/sparta/mypet/domain/post/PostController.java
  src/main/java/com/sparta/mypet/domain/post/PostService.java
  src/main/java/com/sparta/mypet/domain/post/entity/Category.java
  src/main/java/com/sparta/mypet/domain/s3/FileService.java
Labels: refactor

#69 [2024/07/25]refactor/#19 code refactor
  src/main/java/com/sparta/mypet/common/util/ResponseFactory.java
  src/main/java/com/sparta/mypet/domain/auth/UserService.java
  src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeService.java
  src/main/java/com/sparta/mypet/domain/comment/CommentService.java
  src/main/java/com/sparta/mypet/domain/like/LikeRepository.java
  src/main/java/com/sparta/mypet/domain/like/LikeService.java
  src/main/java/com/sparta/mypet/domain/petcare/PetFacilityController.java
  src/main/java/com/sparta/mypet/domain/petcare/PetFacilityService.java
  src/main/java/com/sparta/mypet/domain/petcare/entity/FacilityCategory.java
  src/main/java/com/sparta/mypet/domain/post/PostController.java
  src/main/java/com/sparta/mypet/domain/post/PostService.java
  src/main/java/com/sparta/mypet/domain/post/dto/PostResponseDto.java
  src/main/java/com/sparta/mypet/domain/post/entity/Post.java
  src/main/java/com/sparta/mypet/domain/report/ReportService.java
  src/main/java/com/sparta/mypet/domain/s3/FileResponseDto.java
  src/main/java/com/sparta/mypet/domain/s3/FileService.java
  src/main/java/com/sparta/mypet/domain/s3/S3Config.java
  src/main/java/com/sparta/mypet/security/JwtService.java
  src/main/java/com/sparta/mypet/security/UserDetailsServiceImpl.java
  src/main/java/com/sparta/mypet/security/config/JwtConfig.java
  src/main/resources/data.sql
Labels: refactor

#72 [2024/07/26]feat/#56 report list
  http/backoffice.http
  src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeController.java
  src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeService.java
  src/main/java/com/sparta/mypet/domain/backoffice/dto/ReportListResponseDto.java
  src/main/java/com/sparta/mypet/domain/report/ReportService.java
Labels: feat

#74 [2024/07/26]feat/#57 report status edit
  http/backoffice.http
  http/http-client.env.json
  src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
  src/main/java/com/sparta/mypet/common/exception/custom/ReportNotFoundException.java
  src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeController.java
  src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeService.java
  src/main/java/com/sparta/mypet/domain/backoffice/dto/ReportStatusRequestDto.java
  src/main/java/com/sparta/mypet/domain/report/ReportService.java
  src/main/java/com/sparta/mypet/domain/report/entity/Report.java
Labels: feat

#75 [2024/07/26]refactor/#71 login response
  src/main/java/com/sparta/mypet/domain/auth/AuthController.java
  src/main/java/com/sparta/mypet/domain/auth/AuthService.java
  src/main/java/com/sparta/mypet/domain/auth/dto/LoginResponseDto.java
  src/main/java/com/sparta/mypet/domain/auth/entity/User.java
Labels: feat, refactor

#78 [2024/07/26]fix/#77 post create fix
  src/main/java/com/sparta/mypet/domain/post/PostController.java
Labels: fix

#79 [2024/07/28]fix/#76 login to front
  src/main/java/com/sparta/mypet/domain/auth/AuthController.java
  src/main/java/com/sparta/mypet/domain/auth/AuthService.java
  src/main/java/com/sparta/mypet/security/config/WebSecurityConfig.java
Labels: fix

#81 [2024/07/28]fix/#80 post get islikepost
  http/post.http
  src/main/java/com/sparta/mypet/domain/post/PostController.java
  src/main/java/com/sparta/mypet/domain/post/PostService.java
Labels: fix

#83 [2024/07/29] chore/#82 docker compose mysql
  docker-compose.yml
Labels: chore

#86 [2024/07/26]refactor/#85 postResponseDto postUserId
  src/main/java/com/sparta/mypet/domain/post/dto/PostResponseDto.java
Labels: refactor

#87 [2024/07/30]refactor/#84 auth refresh token
  src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
  src/main/java/com/sparta/mypet/domain/auth/AuthService.java
  src/main/java/com/sparta/mypet/security/JwtService.java
Labels: refactor

#89 [2024/07/30]feat/#88 mypage post
  src/main/java/com/sparta/mypet/domain/auth/UserService.java
Labels: feat

#91 [2024/07/30] fix/#90 Admin, Manager에 사용자 게시물 삭제 권한 부여
  src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
  src/main/java/com/sparta/mypet/domain/auth/entity/UserRole.java
  src/main/java/com/sparta/mypet/domain/post/PostService.java
Labels: fix

#93 [2024/07/30]feat/#92 user update
  http/user.http
  src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
  src/main/java/com/sparta/mypet/common/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/mypet/common/exception/custom/UserNicknameDuplicateException.java
  src/main/java/com/sparta/mypet/common/exception/custom/UserPasswordDuplicationException.java
  src/main/java/com/sparta/mypet/domain/auth/UserController.java
  src/main/java/com/sparta/mypet/domain/auth/UserService.java
  src/main/java/com/sparta/mypet/domain/auth/dto/UserPasswordUpdateRequestDto.java
  src/main/java/com/sparta/mypet/domain/auth/dto/UserUpdateRequestDto.java
  src/main/java/com/sparta/mypet/domain/auth/dto/UserUpdateResponseDto.java
  src/main/java/com/sparta/mypet/domain/auth/entity/User.java
Labels: feat

#97 [2024/07/31]refactor/#96 reportListDto refactor
  src/main/java/com/sparta/mypet/domain/backoffice/dto/ReportListResponseDto.java
Labels: refactor
