Repository MyPet-Sparta5/Mypet, pull requests merged in 2024-08, with the labels that each got.

#114 [2024/08/01]refactor/#113 report mapping
  http/report.http
  src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
  src/main/java/com/sparta/mypet/common/exception/custom/ReportDuplicationException.java
  src/main/java/com/sparta/mypet/common/initialization/DataInitialization.java
  src/main/java/com/sparta/mypet/domain/auth/AuthService.java
  src/main/java/com/sparta/mypet/domain/auth/UserService.java
  src/main/java/com/sparta/mypet/domain/auth/entity/User.java
  src/main/java/com/sparta/mypet/domain/auth/entity/UserStatus.java
  src/main/java/com/sparta/mypet/domain/backoffice/dto/ReportListResponseDto.java
  src/main/java/com/sparta/mypet/domain/backoffice/dto/UserListResponseDto.java
  src/main/java/com/sparta/mypet/domain/report/ReportController.java
  src/main/java/com/sparta/mypet/domain/report/ReportRepository.java
  src/main/java/com/sparta/mypet/domain/report/ReportService.java
  src/main/java/com/sparta/mypet/domain/report/dto/ReportResponseDto.java
  src/main/java/com/sparta/mypet/domain/report/entity/Report.java
Labels: refactor

#117 [2024/08/02] refactor /#116 getposts
  src/main/java/com/sparta/mypet/domain/post/PostService.java
Labels: feat

#118 [2024/08/02]feat/#101 suspension logic
  http/backoffice.http
  src/main/java/com/sparta/mypet/domain/auth/entity/User.java
  src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeController.java
  src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeService.java
  src/main/java/com/sparta/mypet/domain/backoffice/dto/UserStatusRequestDto.java
  src/main/java/com/sparta/mypet/domain/post/PostRepository.java
  src/main/java/com/sparta/mypet/domain/post/PostService.java
  src/main/java/com/sparta/mypet/domain/post/entity/Post.java
  src/main/java/com/sparta/mypet/domain/report/ReportRepository.java
  src/main/java/com/sparta/mypet/domain/report/ReportService.java
  src/main/java/com/sparta/mypet/domain/suspension/SuspensionRepository.java
  src/main/java/com/sparta/mypet/domain/suspension/SuspensionService.java
  src/main/java/com/sparta/mypet/domain/suspension/entity/Suspension.java
Labels: feat

#120 [2024/08/02] feat/#102 backoffice suspension list
  http/backoffice.http
  src/main/java/com/sparta/mypet/domain/auth/entity/User.java
  src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeController.java
  src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeService.java
  src/main/java/com/sparta/mypet/domain/backoffice/dto/SuspensionListResponseDto.java
  src/main/java/com/sparta/mypet/domain/post/entity/Post.java
  src/main/java/com/sparta/mypet/domain/suspension/SuspensionService.java
Labels: feat

#121 [2024/08/02]feat/#112 backoffice post list
  http/backoffice.http
  src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeController.java
  src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeService.java
  src/main/java/com/sparta/mypet/domain/post/PostService.java
Labels: feat

#123 [2024/08/02]feat/#119 post status edit
  http/backoffice.http
  src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
  src/main/java/com/sparta/mypet/common/exception/custom/PostStatusDuplicationException.java
  src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeController.java
  src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeService.java
  src/main/java/com/sparta/mypet/domain/backoffice/dto/PostStatusRequestDto.java
  src/main/java/com/sparta/mypet/domain/post/PostService.java
Labels: feat

#124 [2024/08/02]fix/#122 duplication fix
  build.gradle
  src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
  src/main/java/com/sparta/mypet/common/exception/custom/ReportStatusDuplicationException.java
  src/main/java/com/sparta/mypet/common/exception/custom/UserInfoDuplicationException.java
  src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeService.java
Labels: fix

#126 [2024/08/02]refactor/#125 suspensionResponseDto edit
  src/main/java/com/sparta/mypet/domain/backoffice/dto/SuspensionListResponseDto.java
Labels: refactor

#128 [2024/08/02]refactor/#127 ReportListResponseDto add category
  src/main/java/com/sparta/mypet/domain/backoffice/dto/ReportListResponseDto.java
Labels: refactor

#130 [2024/08/05]refactor/#129 reportList postUserId
  src/main/java/com/sparta/mypet/domain/backoffice/dto/ReportListResponseDto.java
Labels: refactor

#132 [2024/08/06]refactor/#131 PostListResponseDto detail
  src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeController.java
  src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeService.java
  src/main/java/com/sparta/mypet/domain/post/PostController.java
  src/main/java/com/sparta/mypet/domain/post/PostService.java
  src/main/java/com/sparta/mypet/domain/post/dto/PostListResponseDto.java
Labels: refactor

#133 [2024/08/07]feat/#70 kakao login
  build.gradle
  src/main/java/com/sparta/mypet/MypetApplication.java
  src/main/java/com/sparta/mypet/common/config/RedisConfig.java
  src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
  src/main/java/com/sparta/mypet/common/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/mypet/common/exception/custom/SocialAccountLinkedException.java
  src/main/java/com/sparta/mypet/common/util/ResponseFactory.java
  src/main/java/com/sparta/mypet/domain/auth/UserService.java
  src/main/java/com/sparta/mypet/domain/auth/dto/LoginResponseDto.java
  src/main/java/com/sparta/mypet/domain/auth/dto/SignupRequestDto.java
  src/main/java/com/sparta/mypet/domain/auth/dto/UserWithPostListResponseDto.java
  src/main/java/com/sparta/mypet/domain/auth/entity/User.java
  src/main/java/com/sparta/mypet/domain/feign/KakaoAuthApi.java
  src/main/java/com/sparta/mypet/domain/feign/KakaoUserApi.java
  src/main/java/com/sparta/mypet/domain/feign/config/FeignConfiguration.java
  src/main/java/com/sparta/mypet/domain/oauth/KakaoAccountController.java
  src/main/java/com/sparta/mypet/domain/oauth/KakaoAccountService.java
  src/main/java/com/sparta/mypet/domain/oauth/SocialAccountController.java
  src/main/java/com/sparta/mypet/domain/oauth/SocialAccountRepository.java
  src/main/java/com/sparta/mypet/domain/oauth/SocialAccountService.java
  src/main/java/com/sparta/mypet/domain/oauth/dto/KakaoAccountRequestDto.java
  src/main/java/com/sparta/mypet/domain/oauth/dto/KakaoTokenResponseDto.java
  src/main/java/com/sparta/mypet/domain/oauth/dto/KakaoUserInfoDto.java
  src/main/java/com/sparta/mypet/domain/oauth/dto/SocialAccountResponse.java
  src/main/java/com/sparta/mypet/domain/oauth/entity/SocialAccount.java
  src/main/java/com/sparta/mypet/domain/oauth/entity/SocialAccountInfo.java
  src/main/java/com/sparta/mypet/domain/oauth/entity/SocialAccountLeaveRequest.java
  src/main/java/com/sparta/mypet/domain/oauth/entity/SocialType.java
  src/main/java/com/sparta/mypet/security/config/WebSecurityConfig.java
  src/main/resources/application.properties
Labels: feat

#136 [2024/08/07] githubAction 세팅
  .github/workflows/aws.yml
Labels: feat

#140 [2024/08/07] feat/#135 user reactive schedule
  src/main/java/com/sparta/mypet/MypetApplication.java
  src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
  src/main/java/com/sparta/mypet/common/schedule/UserSchedule.java
  src/main/java/com/sparta/mypet/domain/auth/UserRepository.java
  src/main/java/com/sparta/mypet/domain/auth/UserService.java
Labels: feat

#141 [2024/08/07]fix/#137-remove-refresh-token-claim
  src/main/java/com/sparta/mypet/domain/auth/AuthService.java
  src/main/java/com/sparta/mypet/domain/oauth/KakaoAccountService.java
  src/main/java/com/sparta/mypet/security/JwtService.java
  src/main/java/com/sparta/mypet/security/TokenType.java
  src/main/java/com/sparta/mypet/security/util/JwtProvider.java
Labels: fix

#143 [2024/08/07]fix/#142 kakao login bug
  src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
  src/main/java/com/sparta/mypet/domain/auth/UserService.java
  src/main/java/com/sparta/mypet/domain/oauth/KakaoAccountController.java
  src/main/java/com/sparta/mypet/domain/oauth/KakaoAccountService.java
  src/main/java/com/sparta/mypet/domain/oauth/SocialAccountRepository.java
  src/main/java/com/sparta/mypet/domain/oauth/SocialAccountService.java
Labels: bug

#145 [2024/08/08] 🩹 fix : distribution 필드가 누락된 부분 추가
  .github/workflows/aws.yml
Labels: fix

#147 [2024/08/08] 🩹 fix : gradlew 파일 실행 권한 추가
  .github/workflows/aws.yml
Labels: fix

#148 [2024/08/08] fix : ec2 name 수정
  .github/workflows/aws.yml
Labels: fix

#149 [2024/08/08] feat/#88 fix : 부분 수정
  .github/workflows/aws.yml
Labels: fix

#150 [2024/08/08] fix : 부분 수정
  .github/workflows/aws.yml
Labels: fix

#151 [2024/07/30] 🩹 fix : docker 추가
  .github/workflows/aws.yml
Labels: fix

#152 [#146] 🎉 add : Dockerfile 추가
  Dockerfile
Labels: fix

#153 [2024/08/08] fix : dockerHub 레포 이름 수정
  .github/workflows/aws.yml
Labels: fix

#154 [2024/08/08] fix : dockerHub 레포 이름 부분수정
  .github/workflows/aws.yml
Labels: fix

#155 [2024/08/08] fix : dockerHub 레포 이름 부분수정
  .github/workflows/aws.yml
Labels: fix

#156 [2024/08/08] fix : .env 파일 dockerContainer로 복사 코드 추가
  Dockerfile
Labels: fix

#157 [2024/08/08] fix : .env 파일 dockerContainer로 복사 코드 수정
  Dockerfile
Labels: fix

#158 [2024/08/08] 🩹 fix: .env 파일 전달방법 변경
  .github/workflows/aws.yml
  Dockerfile
Labels: fix

#159 [2024/08/08] 🩹 fix .env 파일 전달방법 변경
  .github/workflows/aws.yml
Labels: fix

#160 [2024/08/08]🩹 fix .env 파일 관련 코드 삭제
  .github/workflows/aws.yml
Labels: fix

#161 [2024/08/08] 🩹 fix .env 파일 관련 코드 삭제
  .github/workflows/aws.yml
Labels: fix

#162 [2024/08/08]refactor/#138 separate getuser
  src/main/java/com/sparta/mypet/common/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/mypet/domain/auth/UserController.java
  src/main/java/com/sparta/mypet/domain/auth/UserService.java
  src/main/java/com/sparta/mypet/domain/auth/dto/UserResponseDto.java
  src/main/java/com/sparta/mypet/domain/post/dto/PostMappedUserResponseDto.java
Labels: refactor

#164 [2024/08/08]Feat/#109 email verification
  build.gradle
  http/email.http
  src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
  src/main/java/com/sparta/mypet/common/util/ResponseFactory.java
  src/main/java/com/sparta/mypet/domain/mail/EmailService.java
  src/main/java/com/sparta/mypet/domain/mail/EmailVerificationController.java
  src/main/java/com/sparta/mypet/domain/mail/EmailVerificationService.java
  src/main/java/com/sparta/mypet/domain/mail/config/MailConfig.java
  src/main/java/com/sparta/mypet/domain/mail/dto/VerificationRequest.java
  src/main/java/com/sparta/mypet/security/config/WebSecurityConfig.java
  src/main/resources/application.properties
  src/main/resources/templates/verification-email.html
Labels: feat

#165 [2024/08/09] 🩹 fix add-host 추가
  .github/workflows/aws.yml
Labels: fix

#166 [2024/08/09] 🩹 fix add-host 일부 수정
  .github/workflows/aws.yml
Labels: fix

#167 [2024/08/09]Feat/#139 file compress
  build.gradle
  src/main/java/com/sparta/mypet/common/entity/GlobalMessage.java
  src/main/java/com/sparta/mypet/domain/post/PostService.java
  src/main/java/com/sparta/mypet/domain/post/dto/PostResponseDto.java
  src/main/java/com/sparta/mypet/domain/post/entity/Post.java
  src/main/java/com/sparta/mypet/domain/s3/FileRepository.java
  src/main/java/com/sparta/mypet/domain/s3/FileResponseDto.java
  src/main/java/com/sparta/mypet/domain/s3/FileService.java
  src/main/java/com/sparta/mypet/domain/s3/entity/FileContentType.java
  src/main/java/com/sparta/mypet/domain/s3/entity/UploadedFile.java
  src/main/resources/application.properties
Labels: feat

#169 [2024/08/09] feat/#168 backoffice userlist search
  http/backoffice.http
  src/main/java/com/sparta/mypet/common/config/JPAConfig.java
  src/main/java/com/sparta/mypet/domain/auth/UserRepository.java
  src/main/java/com/sparta/mypet/domain/auth/UserRepositoryQuery.java
  src/main/java/com/sparta/mypet/domain/auth/UserRepositoryQueryImpl.java
  src/main/java/com/sparta/mypet/domain/auth/UserService.java
  src/main/java/com/sparta/mypet/domain/auth/entity/UserSearchCondition.java
  src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeController.java
  src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeService.java
  src/main/java/com/sparta/mypet/domain/backoffice/dto/UserListResponseDto.java
Labels: feat

#171 [2024/08/11] 🩹 fix Cors 설정에 도메인 추가
  src/main/java/com/sparta/mypet/security/config/WebSecurityConfig.java
Labels: fix

#172 [2024/08/08] fix : cors domain fix
  src/main/java/com/sparta/mypet/security/config/WebSecurityConfig.java
Labels: fix

#174 [2024/08/12]refactor/#173-post-soft-delete
  http/post.http
  src/main/java/com/sparta/mypet/domain/post/PostController.java
  src/main/java/com/sparta/mypet/domain/post/PostService.java
  src/main/java/com/sparta/mypet/domain/post/entity/PostStatus.java
Labels: refactor

#178 [2024/08/12]feat/#163 user repository querydsl
  src/main/java/com/sparta/mypet/domain/auth/UserRepository.java
  src/main/java/com/sparta/mypet/domain/auth/UserRepositoryQuery.java
  src/main/java/com/sparta/mypet/domain/auth/UserRepositoryQueryImpl.java
  src/main/java/com/sparta/mypet/domain/auth/entity/User.java
Labels: feat

#179 [#170] 🩹 fix cors설정에 도메인 수정
  src/main/java/com/sparta/mypet/security/config/WebSecurityConfig.java
Labels: fix

#185 [#170] 🩹 fix 포트 수정
  .github/workflows/aws.yml
Labels: fix

#183 [2024/08/12]feat/#182 postList search
  http/post.http
  src/main/java/com/sparta/mypet/domain/auth/UserRepositoryQueryImpl.java
  src/main/java/com/sparta/mypet/domain/post/PostController.java
  src/main/java/com/sparta/mypet/domain/post/PostRepository.java
  src/main/java/com/sparta/mypet/domain/post/PostRepositoryQueryImpl.java
  src/main/java/com/sparta/mypet/domain/post/PostService.java
  src/main/java/com/sparta/mypet/domain/post/dto/PostSearchCondition.java
Labels: feat

#188 [2024/08/12]refactor/#187 separate upload compression
  src/main/java/com/sparta/mypet/domain/post/PostService.java
  src/main/java/com/sparta/mypet/domain/s3/FileService.java
  src/main/java/com/sparta/mypet/domain/s3/ImageCompressionService.java
  src/main/java/com/sparta/mypet/domain/s3/VideoCompressionService.java
Labels: refactor

#190 [2024/08/13]fix/#189 fix url
  src/main/java/com/sparta/mypet/domain/oauth/OAuthController.java
  src/main/java/com/sparta/mypet/domain/oauth/OAuthService.java
  src/main/java/com/sparta/mypet/domain/oauth/dto/KakaoUserInfoDto.java
  src/main/java/com/sparta/mypet/domain/oauth/dto/LeaveCallbackRequestDto.java
  src/main/java/com/sparta/mypet/domain/oauth/dto/TokenResponseDto.java
  src/main/resources/application.properties
Labels: fix

#193 [2024/08/13]fix/#192 signup alert
  src/main/java/com/sparta/mypet/domain/auth/dto/SignupRequestDto.java
Labels: fix

#194 [2024/08/13]feat/#176 backoffice reportList search
  http/backoffice.http
  src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeController.java
  src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeService.java
  src/main/java/com/sparta/mypet/domain/report/ReportRepository.java
  src/main/java/com/sparta/mypet/domain/report/ReportRepositoryQuery.java
  src/main/java/com/sparta/mypet/domain/report/ReportRepositoryQueryImpl.java
  src/main/java/com/sparta/mypet/domain/report/ReportService.java
  src/main/java/com/sparta/mypet/domain/report/dto/ReportSearchCondition.java
Labels: feat

#195 [2024/08/13]feat/#177 backoffice suspensionList search
  http/backoffice.http
  src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeController.java
  src/main/java/com/sparta/mypet/domain/backoffice/BackOfficeService.java
  src/main/java/com/sparta/mypet/domain/suspension/SuspensionRepository.java
  src/main/java/com/sparta/mypet/domain/suspension/SuspensionRepositoryQuery.java
  src/main/java/com/sparta/mypet/domain/suspension/SuspensionRepositoryQueryImpl.java
  src/main/java/com/sparta/mypet/domain/suspension/SuspensionService.java
  src/main/java/com/sparta/mypet/domain/suspension/dto/SuspensionSearchCondition.java
Labels: feat

#197 [2024/08/14]fix/#196 email verification
  src/main/java/com/sparta/mypet/common/util/ResponseFactory.java
  src/main/java/com/sparta/mypet/domain/mail/EmailVerificationController.java
  src/main/java/com/sparta/mypet/domain/mail/EmailVerificationService.java
  src/main/java/com/sparta/mypet/domain/mail/dto/VerificationResponse.java
Labels: feat

#199 [2024/08/14]refactor/#198 video logic refactor
  src/main/java/com/sparta/mypet/domain/s3/FileService.java
  src/main/java/com/sparta/mypet/domain/s3/entity/FileContentType.java
Labels: refactor

#203 [2024/08/18]refactor/#201 post querydsl
  http/report.http
  src/main/java/com/sparta/mypet/common/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/mypet/domain/post/PostRepository.java
  src/main/java/com/sparta/mypet/domain/post/PostRepositoryQuery.java
  src/main/java/com/sparta/mypet/domain/post/PostRepositoryQueryImpl.java
  src/main/java/com/sparta/mypet/domain/post/PostService.java
Labels: refactor

#204 [2024/08/18]refactor/#202 report querydsl
  src/main/java/com/sparta/mypet/domain/report/ReportRepository.java
  src/main/java/com/sparta/mypet/domain/report/ReportRepositoryQuery.java
  src/main/java/com/sparta/mypet/domain/report/ReportRepositoryQueryImpl.java
  src/main/java/com/sparta/mypet/domain/report/ReportService.java
  src/main/java/com/sparta/mypet/domain/suspension/SuspensionService.java
Labels: refactor

#207 [2024/08/19]fix/#206 update facility data
  src/main/resources/data.sql
Labels: feat
